### ISSUE TITLE
Definir como será acompanhado caixa e-mail `faleconosco`

### ISSUE THREAD

**Issue by gabrielbdornas** [meadapt/meadapt.com#24]
See #19 

@raianecardoso, como já temos a caixa de email `faleconosco` agora temos que definir como acompanharemos. Pensando que estamos publicando posts e que as pessoas podem querer entrar com contato (deus abençoe)!

Acho que uma boa estratégia seria ligar esta caixa para nossos emails pessoais. Assim, conseguiríamos visualizar sem precisar entrar de fato na mesma. Por outro lado, isso pode ser um risco, tendo em vista que podemos, você e eu, respondermos a mesma mensagem. Ou seja, temos que pensar.

**Comment by raianecardoso** [comment]
@gabrielbdornas, acho que incialmente não teremos tantas demandas e conseguiremos ir controlando isso. De todo modo, criei uma tag 'respondido' para marcamos os e-mails. 

No entanto, verifiquei que o encaminhamento do e-mail é uma opção premium 🤡 . Ou seja, vamos precisar entrar rotineiramente nesse e-mail. Vou tentar criar esse hábito!

<img width="1440" alt="Captura de Tela 2024-09-23 às 20 25 12" src="https://github.com/user-attachments/assets/8fc052ba-3015-4fdd-a425-91a9365415c7">

**Comment by raianecardoso** [comment]
@gabrielbdornas, 

Então podemos fechar no esquema de semanas do mês? 
- do dia 1º ao 15, @raianecardoso  responsável. 
- do dia 16 ao 30/31, @gabrielbdornas responsável. 

Nós dois usamos a TAG e-mail respondido pra controle.  No mais, por mais que seria excelente automatizar essa ação, acho que tem que ser uma rotina nossa, assim como abrir o GitHub.

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas,
> 
> Então podemos fechar no esquema de semanas do mês?
> 
> * do dia 1º ao 15, @raianecardoso  responsável.
> * do dia 16 ao 30/31, @gabrielbdornas responsável.
> 
> Nós dois usamos a TAG e-mail respondido pra controle. No mais, por mais que seria excelente automatizar essa ação, acho que tem que ser uma rotina nossa, assim como abrir o GitHub.

@raianecardoso achei o serviço gratuito [pipedream](https://pipedream.com/). Nele consegui configurar uma integração para recebermos emails (nossas contas pessoal gmail) toda vez que um faleconosco chegar.

Acho que podemos manter as datas acima para quem ficará responsável por responder. O que acha?

Obs.: Foi facinho de configurar!! É tipo o automate web. Pelo último teste que fiz está funcionando, mas não custa também entrarmos diariamente para conferir!
