### ISSUE TITLE
Vídeos youtube sem thumbnail no post Aprenda RPA com Power Automate e construa sua primeira automação do zero

### ISSUE THREAD

**Issue by gabrielbdornas** [meadapt/meadapt.com#42]
See #33

**Comment by gabrielbdornas** [comment]
Aguardando logomarca para criar thumbnails.

**Comment by gabrielbdornas** [comment]
@raianecardoso, marcando você aqui!

**Comment by raianecardoso** [comment]
Vídeos com Thumbnail e descrição completa! 🚀

**Comment by gabrielbdornas** [comment]
> Vídeos com Thumbnail e descrição completa! 🚀

Cara, ficou muuuuuuito bom! Profissional. Não conseguiria fazer isso nunca sozinho! Valeu demais
